apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-jenkins
  template:
    metadata:
      labels:
        app: hello-jenkins
    spec:
      containers:
      - name: hello-jenkins
        image: ${output.ecr_repository_url}
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: aws-ecr-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: hello-jenkins
spec:
  selector:
    app: hello-jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
